### ISSUE TITLE
Display Wrong Place

### ISSUE THREAD

**Issue by uzeyirdestan** [andrew/ar-drone-gps#1]
Hi
 I just setup your packages and browser shows me nearly 10 mil away. Also my Ar Drone wont take affect when i created a route to follow.

**Comment by wiseman** [comment]
Is the LED on your flight recorder module blinking green, indicating a satellite lock?

You might try flying the drone for a minute with the official iPad app first, which will upload recent satellite position information to the drone and help it get a GPS lock faster.

**Comment by andrew** [comment]
As @wiseman said, I suspect it's that the drone doesn't have a very good gps signal, does it have an accurate location when flying with the app?

**Comment by uzeyirdestan** [comment]
Yeah it has. I fly it with my ipad with no problem.Coordinates also the true.But when i try on the computer it's shows me far away from my real location.Interesting thing that when i get the coordinates from browser and search from google it shows the exact place. But leaflet shows wrong place.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
