### ISSUE TITLE
emitting 'go' from index.html has no handler 

### ISSUE THREAD

**Issue by seiflotfy** [andrew/ar-drone-gps#2]
when emitting go in index.html i noticed there is no handler for it in server.js. Is there a reason for that?

**Comment by andrew** [comment]
@seiflotfy I suspect it was an oversight on my part, I built the app pretty quickly and there could be all kinds of bugs hidden away in there!

**Comment by seiflotfy** [comment]
no worries dude, it still rocks I am just trying to found out how I can send the drone my gps data and tell it to move there. Any idea?

**Comment by wiseman** [comment]
As far as I know there's no way to do that using the API that [node-ar-drone](https://github.com/felixge/node-ar-drone) (which is what ar-drone-gps uses) connects to, but you can do this using the [Mavlink](http://qgroundcontrol.org/mavlink/start) protocol that the drone supports.

Unfortunately Mavlink isn't as easy to use as node-ar-drone.  You could start with [QGroundControl](http://www.qgroundcontrol.org/), which is a ground control station (GCS) that speaks mavlink and is known to work with the AR.Drone.

[mavelous](https://github.com/wiseman/mavelous) is a browser-based GCS that can do mavlink, but I haven't tried it with an AR.Drone.

If you want to write your own code that does mavlink, there are pretty good Python, C, and Java libraries.  I've seen javascript libraries, but I haven't tried them and don't know how complete they are.

**Comment by andrew** [comment]
This project implements that in a very basic way, mainly within this function: https://github.com/andrew/ar-drone-gps/blob/master/server.js#L86-L122

It could be extracted into smaller lib to do just that, or hooked into https://github.com/eschnou/ardrone-autonomy

**Comment by seiflotfy** [comment]
@andrew AFAICT that is a slick implementation. So basically you are telling it to move 0.05 in a direction then check again the navdata? right?

**Comment by andrew** [comment]
Yeah, it basically turns the drone to point towards the destination and start moving forwards, then corrects the direction every time it receives an update on it's current position, until it's within a certain distance of the target.

**Comment by seiflotfy** [comment]
is the yaw in anyway related to a compass?

**Comment by seiflotfy** [comment]
@wiseman dude you rock :D I am following some other stuff you have been writing about. Any news on https://github.com/felixge/node-ar-drone/issues/74? Also any good tutorial on mavlink. I really dont understand it

**Comment by andrew** [comment]
yeah, yaw is the angle of rotation from north I believe.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
