### ISSUE TITLE
Ardrone velocity

### ISSUE THREAD

**Issue by ibekmezci** [andrew/ar-drone-gps#4]
I thank you for this great code. However, when I fly my Ardrone with this code, its velocity is not constant. What should I do for constant velocity flight?

**Comment by andrew** [comment]
The code here: https://github.com/andrew/ar-drone-gps/blob/master/server.js#L115 should make it move at a constant speed, although the frequent changes in direction could be slowing it down, it's hard to tell without more information.

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
